name: preview

on:
  push:
    branches:
      - "staging/*"

jobs:
  preview:
    name: preview
    runs-on: macos-latest
    steps:
      - name: üèó Setup repo
        uses: actions/checkout@v2

      - name: üèó Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: üèó Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: üì¶ Install dependencies
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: npm install --force

      - name: üöÄ Publish preview
        run: export SENTRY_ORG=${{secrets.SENTRY_ORG}} && export SENTRY_APP_PROJECT=${{secrets.SENTRY_APP_PROJECT}} && export SENTRY_APP_AUTH_TOKEN=${{secrets.SENTRY_APP_AUTH_TOKEN}} && npm run preview:app

      - name: üë∑ Create preview comment
        uses: expo/expo-github-action/preview-comment@v7
        id: preview
        with:
          project: ./apps/soratani
          comment: false
          channel: staging


      - name: üí¨ Comment in Slack
        uses: slackapi/slack-github-action@v1.17.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          channel-id: C03DY3QTBTQ
          slack-message: 'New deployment is ready!\n- Preview: ${{ steps.preview.outputs.projectLink }}'

  serverless:
    name: serverless
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2

      - name: install serverless
        run: npm install -g serverless


      - name: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install dependency
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: npm install --force

      - name: build server
        run: npm run build:server

      - name: deploy serverless
        run: sls deploy
        env:
          STAGE: test
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
